Frontend Docker file updated

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,43 +1,74 @@
-# Use Ubuntu as the base image
-FROM ubuntu:25.04
+FROM node:22-alpine AS base
 
-# Install required system dependencies
-RUN apt update && \
-    apt install -y --no-install-recommends \
-    build-essential \
-    gcc \
-    curl \
-    gnupg2 \
-    ca-certificates \
-    apt-transport-https \
-    && apt clean \
-    && rm -rf /var/lib/apt/lists/*
-
-# Install Node.js 20.2.0
-RUN curl -sL https://deb.nodesource.com/setup_22.x | bash -
-RUN apt install -y nodejs
-
-# Install yarn
-RUN npm install -g yarn
-
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Copy the .env file to /app
-# COPY frontend/.env /app/.env
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
-# Copy package files
-COPY frontend/package*.json /app
-COPY frontend/yarn.lock /app
+# Copy EntryPoint script
+# COPY entrypoint.sh ./
+# RUN chmod +x ./entrypoint.sh
+# # COPY --chmod=755 frontend/entrypoint.sh /app/entrypoint.sh
 
-# Install dependencies
-RUN yarn install
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-# Add the entrypoint script and make it executable
-COPY frontend/entrypoint.sh /app/entrypoint.sh
-COPY --chmod=755 frontend/entrypoint.sh /app/entrypoint.sh
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# Copy the rest of the application files
-COPY frontend /app
+RUN yarn build
 
-# Set the entrypoint
-ENTRYPOINT [ "sh", "-c", "/app/entrypoint.sh" ]
+# If using npm comment out above and use below instead
+# RUN npm run build
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=development
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT=3000
+# set hostname to localhost
+ENV HOSTNAME="0.0.0.0"
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+CMD ["node", "server.js"]
+# CMD ["ls", "-la", "/app"]
+# ENTRYPOINT [ "sh", "-c", "/app/entrypoint.sh" ]
+
